#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/bs-remnanode
CONFIG_FILE=/etc/config/bs-remnanode

start_service() {
    # Read UCI config
    local node_port secret_key xtls_api_port xray_bin

    config_load bs-remnanode
    config_get node_port   main node_port   "2222"
    config_get secret_key  main secret_key  ""
    config_get xtls_api_port main xtls_api_port "61000"
    config_get xray_bin    main xray_bin    "/usr/bin/xray"

    if [ -z "$secret_key" ]; then
        echo "bs-remnanode: SECRET_KEY is not set in /etc/config/bs-remnanode"
        return 1
    fi

    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param env \
        NODE_PORT="$node_port" \
        SECRET_KEY="$secret_key" \
        XTLS_API_PORT="$xtls_api_port" \
        XRAY_BIN="$xray_bin"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # xray will be killed by the manager when bs-remnanode exits
    return 0
}

reload_service() {
    stop
    start
}
